apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 2 # 10 pod olusurken ayni anda kacar kacar olusacak
  completions: 10 #kac tane istiyoruz basarili pod sayisi
  backoffLimit: 5 # kackere hata olursa job fail olur, devam etme
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never #OnFailure 